# Generated by Django 4.1.5 on 2023-06-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lablog',
            name='lab_log_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='patlog_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='payerscheme',
            name='payerId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='modeId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prcp_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='sl_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
