# Generated by Django 4.1.5 on 2023-06-18 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_servicelog_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpy_id', models.CharField(max_length=20, unique=True)),
                ('billable_amount', models.IntegerField(default=0)),
                ('cash_value', models.IntegerField(default=0)),
                ('epay_value', models.IntegerField(default=0)),
                ('invoice_value', models.IntegerField(default=0)),
                ('transaction_code', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pat_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patientlog')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.payerscheme')),
            ],
        ),
        migrations.CreateModel(
            name='CashOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cao_id', models.CharField(max_length=10, unique=True)),
                ('option_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.payerscheme')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
