# Generated by Django 4.1.5 on 2023-06-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_debitpaymentlog_cashoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashOptions',
            new_name='CashOption',
        ),
    ]
