# Generated by Django 4.1.5 on 2023-06-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_cashoptions_cashoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitpaymentlog',
            name='transaction_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
