# Generated by Django 4.1.5 on 2023-06-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_debitpaymentlog_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitpaymentlog',
            name='cash_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cashoption'),
        ),
    ]
