# Generated by Django 4.1.5 on 2023-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_debitpaymentlog_cash_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitpaymentlog',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
