# Generated by Django 4.1.5 on 2023-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_debitpaymentlog_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
