# Generated by Django 4.1.5 on 2023-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_servicelog_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
