# Generated by Django 4.1.5 on 2023-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_service_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_group',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
