# Generated by Django 4.1.5 on 2023-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_service_service_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientlog',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
