# Generated by Django 4.1.5 on 2023-06-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_patientlog_options_drug_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientlog',
            options={},
        ),
    ]
