# Generated by Django 4.1.5 on 2023-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_patientlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlog',
            name='cash_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
