# Generated by Django 4.1.5 on 2023-07-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_patientlog_emergency_code_facilityinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityInfo',
            new_name='Facility',
        ),
    ]
