# Generated by Django 4.1.5 on 2023-07-06 13:04

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_facilityinfo_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_logo',
            field=models.ImageField(default='logo.png', upload_to=base.models.upload_path_handler_fac),
        ),
        migrations.CreateModel(
            name='EmergencyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=10, unique=True)),
                ('code_name', models.CharField(max_length=15, unique=True)),
                ('code_number', models.IntegerField(default=0)),
                ('code_description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code_responders', models.ManyToManyField(to='base.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
