# Generated by Django 4.1.5 on 2023-07-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_facility_created_alter_facility_facility_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_phone3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
