# Generated by Django 4.1.5 on 2023-07-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_patientlog_emergency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='emergency_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.emergencycode'),
        ),
    ]
