# Generated by Django 4.1.5 on 2023-07-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_patientlog_emergency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlog',
            name='pharmacy_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
