# Generated by Django 4.1.5 on 2023-07-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_patientlog_pharmacy_cleared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlog',
            name='pharmacy_cleared',
        ),
        migrations.AddField(
            model_name='patientlog',
            name='dpt_path',
            field=models.ManyToManyField(blank=True, to='base.department'),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cur_dept', to='base.department'),
        ),
    ]
