# Generated by Django 4.1.5 on 2023-07-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_dpt_path_patientlog_involved_depts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lablog',
            name='patient',
        ),
        migrations.AddField(
            model_name='lablog',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lablog',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.servicelog'),
        ),
    ]
