# Generated by Django 4.1.5 on 2023-07-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_attendancelog_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.TimeField(),
        ),
    ]
