# Generated by Django 4.1.5 on 2023-07-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_attendancelog_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
