# Generated by Django 4.1.5 on 2023-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='from_date',
            field=models.DateTimeField(),
        ),
    ]
