# Generated by Django 4.1.5 on 2023-07-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_payroll_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
