# Generated by Django 4.1.5 on 2023-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_payroll_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
