# Generated by Django 4.1.5 on 2023-07-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_payroll_cleared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashoption',
            old_name='cao_id',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='departmentId',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='emergencycode',
            old_name='code_id',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='recId',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='financialaccount',
            old_name='acc_id',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='leavestatus',
            old_name='status_id',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='leave_type_id',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='payerscheme',
            old_name='payerId',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='paymentmode',
            old_name='modeId',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceId',
            new_name='rec_id',
        ),
    ]
