# Generated by Django 4.1.5 on 2023-07-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_imaginglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientlog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
