# Generated by Django 4.1.5 on 2023-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_patient_updated_patientlog_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
