# Generated by Django 4.1.5 on 2023-07-19 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_employee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='cashoption',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='employeeevaluation',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='debitpaymentlog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imaginglog',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavestatus',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
