# Generated by Django 4.1.5 on 2023-07-19 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_rename_user_attendancelog_added_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycode',
            old_name='user',
            new_name='added_by',
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(max_length=10, unique=True)),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
