# Generated by Django 4.1.5 on 2023-07-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_dentallog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='generates_income',
            new_name='handles_patient',
        ),
    ]
