# Generated by Django 4.1.5 on 2023-09-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_patientlog_total_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='handles_drugs',
            field=models.BooleanField(default=False),
        ),
    ]
