# Generated by Django 4.1.5 on 2023-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_department_handles_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='role',
            field=models.CharField(choices=[('null', 'null'), ('consultation', 'consultation'), ('pharmacy', 'pharmacy'), ('nursing', 'nursing'), ('cashier', 'cashier')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='handles_drugs',
            field=models.BooleanField(default=False, help_text='This should only be activated for pharmacy.'),
        ),
    ]
