# Generated by Django 4.1.5 on 2023-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_department_role_alter_department_handles_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlog',
            name='admission_category',
            field=models.CharField(choices=[('OUTPATIENT', 'outpatient'), ('INPATIENT', 'inpatient')], default='OUTPATIENT', max_length=15),
        ),
        migrations.AlterField(
            model_name='department',
            name='role',
            field=models.CharField(choices=[('null', 'None'), ('consultation', 'consultation'), ('pharmacy', 'pharmacy'), ('nursing', 'nursing'), ('cashier', 'cashier'), ('hr', 'human resource'), ('laboratory', 'laboratory'), ('imaging', 'sonography & imaging'), ('dental', 'dental services'), ('I.T', 'I.T'), ('sales', 'sales & marketing'), ('finance', 'finance')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admission_category',
            field=models.CharField(choices=[('OUTPATIENT', 'outpatient'), ('INPATIENT', 'inpatient')], default='OUTPATIENT', max_length=15),
        ),
    ]
