# Generated by Django 4.1.5 on 2023-09-09 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_patientlog_admission_category_alter_department_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('admission_category', models.CharField(choices=[('OUTPATIENT', 'outpatient'), ('INPATIENT', 'inpatient')], default='OUTPATIENT', max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('description', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.payerscheme')),
                ('service', models.ManyToManyField(blank=True, to='base.service')),
            ],
        ),
    ]
