# Generated by Django 4.1.5 on 2023-09-10 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apt_doc', to=settings.AUTH_USER_MODEL),
        ),
    ]
