# Generated by Django 4.1.5 on 2023-09-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bed_count', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], default='Regular', max_length=100)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
