# Generated by Django 4.1.5 on 2023-09-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(max_length=10, unique=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('condition', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patientlog')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ward')),
            ],
        ),
    ]
