# Generated by Django 4.1.5 on 2023-09-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_inpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient',
            name='room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ward'),
        ),
    ]
