from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name='home'),
    path('reception',views.reception,name='reception'),
    path('reception/new-patient',views.rec_new_patient,name='new-pat'),
    path('reception/patient-inventory',views.reception_pat_inventory,name='rec-pat-inventory'),
    path('reception/patient-file/<str:pk>/',views.rec_show_patient,name='rec-show-patient'),
    path('reception/search-patient',views.reception_search_patient,name='rec-search-patient'),
    
    path('cashier',views.cashier,name='cashier'),
    path('cashier/patient-file/<str:pk>/',views.cashierPatFile,name='cash-patient-file'),
    path('cashier/cash-receipts',views.cashierReceiptsList,name='cash-receipts'),
    path('cashier/print-receipt/<str:pk>/',views.cashierReceipt,name='cash-receipt'),
    path('cashier/finalize-payment/<str:pk>/',views.cashFinalize,name='cash-finalize'),
    path('cashier/cash-pending',views.cashierPending,name='cash-pending'),
    path('cashier/cash-cleared',views.cashierCleared,name='cash-cleared'),
    path('cashier/cash-uncompleted',views.cashierUncompleted,name='cash-uncompleted'),
    path('cashier/patient-invoices',views.cashierInvoicesList,name='cash-patient-invoices'),
    path('cashier/print-patient-invoice/<str:pk>/',views.patientInvoice,name='cash-patient-invoice'),
    
    path('finance',views.finance,name='finance'),
    path('finance/daily-collection-report',views.financeDailyCollection,name='daily-collection-report'),
    
    path('hr',views.humanResource,name='hr'),
    path('hr/manage-employees',views.hrManageEmployees,name='hr-manage-employees'),
    path('hr/new-employee',views.hrNewEmployee,name='hr-new-employee'),
    path('hr/attendance',views.hrAttendance,name='hr-attendance'),
    path('hr/attendance-new',views.hrAttendanceNew,name='hr-attendance-new'),
    path('hr/attendance-file/<str:pk>/',views.hrAttendanceFile,name='hr-attendance-file'),
    path('hr/attendance-daily-list',views.hrAttendanceDaily,name='hr-attendance-daily-list'),
    path('hr/attendance-all',views.hrAttendanceAll,name='hr-attendance-all'),
    path('hr/evaluation',views.hrEmployeeEvaluation,name='hr-evaluation'),
    path('hr/evaluation-list',views.hrEmployeeEvaluationList,name='hr-evaluation-list'),
    path('hr/completed-evaluations',views.hrCompletedEvaluations,name='hr-completed-evaluations'),
    path('hr/new-evaluation-file/<str:pk>/',views.hrEmployeeEvaluationFile,name='hr-new-evaluation-file'),
    path('hr/open-evaluation-file/<str:pk>/',views.hrOpenEvaluationFile,name='hr-open-evaluation-file'),
    path('hr/employee-file/<str:pk>/',views.hrEmployeeFile,name='hr-employee-file'),
    path('hr/employee-list',views.hrEmployeeList,name='hr-employee-list'),
    path('hr/leave-mgm',views.hrLeaveMgm,name='hr-leave-mgm'),
    path('hr/leave-requests/<str:pk>/',views.hrLeaveRequests,name='hr-leave-requests'),
    path('hr/add-leave',views.hrAddLeave,name='hr-add-leave'),
    path('hr/leave-request-file/<str:pk>/',views.hrLeaveRequestFile,name='hr-leave-request-file'),
    path('hr/payroll',views.hrPayroll,name='hr-payroll'),
    path('hr/add-payroll',views.hrAddPayroll,name='hr-add-payroll'),
    path('hr/payroll-records/<str:pk>/',views.hrPayrollRecs,name='hr-payroll-records'),
    path('hr/payroll-record-file/<str:pk>/',views.hrPayrollRecordFile,name='payroll-record-file'),
    
    path('med',views.med,name='med'),
    path('med/med-uncompleted',views.medUncompleted,name='med-uncompleted'),
    path('med/patient-file/<str:pk>/',views.medPatientFile,name='med-patient-file'),
    path('med/patient/prc/<str:pk>/',views.medEditPrescriptions,name='edit-prc'),
    path('med/patient/del-prc/<str:pk>/',views.delPrescriptions,name='del-prc'),
    path('med/patient/del-ser/<str:pk>/',views.delService,name='del-ser'),
    path('med/patient/service/<str:pk>/',views.medEditServices,name='edit-services'),
    path('med/med-completed',views.medCompleted,name='med-completed'),
    
    path('pharmacy',views.pharmacy,name='pharmacy'),
    path('pharmacy/pharmacy-uncompleted',views.pharmacyUncompleted,name='pharmacy-uncompleted'),
    path('pharmacy/pharmacy-completed',views.pharmacyCompleted,name='pharmacy-completed'),
    path('pharmacy/pharmacy-stock-records',views.pharmacyStocksPage,name='pharmacy-stocks-page'),
    path('pharmacy/pharmacy-drugs-inv',views.pharmacyDrugsInventory,name='pharmacy-drugs-inventory'),
    path('pharmacy/pharmacy-adjustment-listing',views.pharmacyStocksAdjustmentListing,name='pharmacy-adjustment-listing'),
    path('pharmacy/adjust-drug/<str:pk>/',views.pharmacyAdjustDrug,name='pharmacy-adjust-drug'),
    path('pharmacy/stock-take/',views.pharmacyStockTake,name='pharmacy-stock-take'),
    path('pharmacy/add-drug',views.pharmacyAddDrug,name='pharmacy-new-drug'),
    path('pharmacy/patient-file/<str:pk>/',views.pharmacyPatFile,name='pharmacy-patient-file'),
        
    path('nurse',views.nurse,name='nurse'),
    path('nurse/unattended',views.nurseUncompleted,name='nurse-unattended'),
    path('nurse/patient-file/<str:pk>/',views.nursePatientFile,name='nurse-patient-file'),
    
    path('investigations',views.investigations,name='investigations'),
    path('investigations/completed',views.investigationsCompleted,name='investigations-completed'),
    path('investigations/uncompleted',views.investigationsUncompleted,name='investigations-uncompleted'),
    path('investigations/pat/<str:pk>/',views.investigationsPatFile,name='investigations-pat-file'),
    
    path('imaging_and_radiography',views.imaging_and_radiography,name='imaging_and_radiography'),
    path('imaging_and_radiography/completed',views.imagingCompleted,name='imaging-completed'),
    path('imaging_and_radiography/uncompleted',views.imagingUncompleted,name='imaging-uncompleted'),
    path('imaging_and_radiography/pat/<str:pk>/',views.imagingPatFile,name='imaging-pat-file'),
    
    path('dental',views.dental,name='dental'),
    path('dental/completed',views.dentalCompleted,name='dental-completed'),
    path('dental/uncompleted',views.dentalUncompleted,name='dental-uncompleted'),
    path('dental/pat/<str:pk>/',views.dentalPatFile,name='dental-pat-file'),
    
    path('hosp-admin',views.hospAdmin,name='hosp-admin'),
    path('hosp-admin/add-user',views.addUser,name='admin-new-account'),
    path('hosp-admin/users-list',views.usersList,name='admin-users-list'),
    path('hosp-admin/patientlogs',views.patientLogsList,name='admin-patientlogs-list'),
    path('hosp-admin/patient-log-file/<str:pk>/',views.AdminPatientLogFile,name='admin-patient-log-file'),
    path('hosp-admin/settings',views.adminSettings,name='admin-settings'),
    path('hosp-admin/settings/edit/<str:table>/<str:pk>/',views.settingsEdit,name='admin-settings-edit'),
    path('hosp-admin/settings/delete/<str:table>/<str:pk>/',views.settingsDelete,name='admin-settings-delete'),
    path('hosp-admin/settings/add/<str:table>/',views.settingsAdd,name='admin-settings-add'),
    path('hosp-admin/settings/departments',views.settingsListingDepartments,name='admin-settings-departments'),
    path('hosp-admin/settings/services',views.settingsListingServices,name='admin-settings-services'),
    path('hosp-admin/settings/facilities',views.settingsListingFacility,name='admin-settings-facilities'),
    path('hosp-admin/settings/creditors',views.settingsListingCreditors,name='admin-settings-creditors'),
    path('hosp-admin/settings/suppliers',views.settingsListingSuppliers,name='admin-settings-suppliers'),
    path('hosp-admin/settings/payment-modes',views.settingsListingPaymentModes,name='admin-settings-payment-modes'),
    path('hosp-admin/settings/financial-accounts',views.settingsListingFinancialAccounts,name='admin-settings-financial-accounts'),
    path('hosp-admin/settings/cash-options',views.settingsListingCashOptions,name='admin-settings-cash-options'),
    path('hosp-admin/settings/emergency-codes',views.settingsListingEmergencyCodes,name='admin-settings-emergency-codes'),
    path('hosp-admin/settings/leave-statuses',views.settingsListingLeaveStatuses,name='admin-settings-leave-statuses'),
    path('hosp-admin/settings/leave-types',views.settingsListingLeaveTypes,name='admin-settings-leave-types'),
    path('hosp-admin/settings/groups',views.group_permissions_view,name='admin-settings-groups'),
    path('hosp-admin/settings/edit-group-permissions/<str:pk>/', views.edit_group_permissions, name='edit-group-permissions'),
    path('hosp-admin/settings/create-group/', views.create_group, name='create-group'),
    path('hosp-admin/settings/add-users-to-group/<str:pk>/', views.add_users_to_group, name='add-users-to-group'),
    path('osp-admin/settings/delete-group/<str:pk>/', views.delete_group, name='delete-group'),
    path('no-permission/', views.no_permission, name='no-permission'),
    path('account/edit/', views.editProfile, name='edit-profile'),
    path('account/forgot-password/', views.forgot_password, name='forgot-password'),
    path('account/change-password/', views.change_password, name='change-password'),
    
    path('login',views.hospLogin,name='login'),
    path('signout',views.hospLogout,name='signout'),
]